site_name: FAIR-by-Design Training of Trainers
docs_dir: resources
theme:
 name: material
plugins:
  - tags
  - exclude:
      glob:
        - "*Activities/*"
        - "*Assessment/*"
        - "*Templates/*"
        - "*.tmp"
        - "*.pdf"
        - "*.gz"
        - "*.pptx"
        - "*_plan.md"
      regex:
        - '.*\.(tmp|bin|tar)$'