site_name: FAIR-by-Design Training of Trainers
docs_dir: resources
theme:
 name: material
plugins:
  - tags
  - mike:
      version_selector: true
  - exclude:
      glob:
        - "*Activities/*"
        - "*Assessment/*"
        - "*Templates/*"
        - "*.tmp"
        - "*.pdf"
        - "*.gz"
        - "*.pptx"
        - "*_plan.md"
        - "*_facilitator_guide.md"
        - "FAIR-by-Design_ToT_syllabus.md"
      regex:
        - '.*\.(tmp|bin|tar)$'
extra:
  version:
    provider: mike