name: Get current DOI
on:
  workflow_dispatch:
  workflow_call:

jobs:
  get_current_doi:
    name: Get current DOI
    runs-on: ubuntu-22.04
    outputs:
      CURRENT_DOI: ${{ steps.current_doi.outputs.EXTRACTED_CURRENT_DOI }}
    steps:
      - name: Checkout master
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: main

      - name: Get current DOI
        uses: mikefarah/yq@v4.34.2
        id: current_doi
        with:
          cmd: "echo EXTRACTED_CURRENT_DOI=$(yq '.doi' CITATION.cff) >> $GITHUB_OUTPUT"