name: Release
on:
  workflow_dispatch:
  release:
    types:
      - released

jobs:
  deploy_docs:
    name: Deploy docs
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          cache: 'pip'
          cache-dependency-path: requirements.txt
          python-version: '3.9'

      - name: Install Python dependencies
        run: pip install -r requirements.txt

      - name: Configure Git user
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"

      - name: Deploy with mike
        run: |
          mike deploy --rebase --push --update-aliases ${{ github.event.release.tag_name }}
  zenodo_publish:
    name: Publish on Zenodo
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Create a draft on Zenodo Sandbox
        uses: zenodraft/action@0.10.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ZENODO_SANDBOX_ACCESS_TOKEN: ${{ secrets.ZENODO_SANDBOX_ACCESS_TOKEN }}
        with:
          compression: zip
          # metadata: .zenodo.json
          publish: false
          upsert-doi: true
          upsert-location: doi
          sandbox: true
          verbose: true

      # - name: Create a draft on Zenodo Sandbox
      #   uses: megasanjay/upload-to-zenodo@v2.0.1
      #   with:
      #     github_token: ${{ secrets.GITHUB_TOKEN }}
      #     zenodo_token: ${{ secrets.ZENODO_SANDBOX_ACCESS_TOKEN }}
      #     zenodo_publish: false
      #     zenodo_sandbox: true
      #     update_metadata_files: true
      #     citation_cff: true

      # - name: Get the output doi
      #   run: echo "The released doi was ${{ steps.release.outputs.doi }}"