name: Deposit on Zenodo
on:
  workflow_call:
    secrets:
      ZENODO_SANDBOX_ACCESS_TOKEN:
        required: true
  # release:
  #   types:
  #     - published
jobs:
  zenodo_publish:
    name: Publish on Zenodo
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: main

      - name: Create a draft on Zenodo Sandbox
        uses: zenodraft/action@0.10.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ZENODO_SANDBOX_ACCESS_TOKEN: ${{ secrets.ZENODO_SANDBOX_ACCESS_TOKEN }}
        with:
          compression: zip
          metadata: .zenodo.json
          publish: false
          upsert-doi: true
          upsert-location: doi
          sandbox: true
          verbose: true
          # collection: 123456789 # Docs: https://github.com/marketplace/actions/zenodraft#collection