name: Deposit on Zenodo
on:
  workflow_call:
    secrets:
      ZENODO_SANDBOX_ACCESS_TOKEN:
        required: true
jobs:
  zenodo_publish:
    name: Publish on Zenodo
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: main

      - name: Get previous tag (if any)
        id: previoustag
        uses: "WyriHaximus/github-action-get-previous-tag@v1"
        with:
          fallback: 999.50.60 # Optional fallback tag to use when no tag can be found

      - name: Get collection id
        run: |
          echo "The previous release is: ${{ steps.previoustag.outputs.tag }}"

      - name: Create a draft on Zenodo Sandbox
        uses: zenodraft/action@0.10.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ZENODO_SANDBOX_ACCESS_TOKEN: ${{ secrets.ZENODO_SANDBOX_ACCESS_TOKEN }}
        with:
          compression: zip
          metadata: .zenodo.json
          publish: false
          upsert-doi: true
          upsert-location: doi
          sandbox: true
          verbose: true
          collection: ''
          # collection: 123456789 # Docs: https://github.com/marketplace/actions/zenodraft#collection